title: "fieldnotes"
description: "a public record of service work, research, and reflections — all grounded in non-zero days."
author: "manahil"
email: "mawan@gm.slc.edu"
baseurl: ""
url: "https://m4n4h1l.github.io/fieldnotes/"

theme: minima
markdown: kramdown

plugins:
  - jekyll-feed

sass:
  style: compressed

include:
  - assets/css
