title: "fieldnotes"
description: "a public record of service work, research, and reflections... all grounded in non-zero days."
author: manahil
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed

sass:
  style: compressed

include:
  - assets/css
