title: "fieldnotes"
description: "a public record of service work, research, and reflections — all grounded in non-zero days."
author: "manahil"
baseurl: "" # for root site
url: "https://m4n4h1l.github.io"

remote_theme: "jekyll/minima@1e8a445"
markdown: kramdown

plugins:
  - jekyll-feed

sass:
  style: compressed

include:
  - assets/css
